### ISSUE TITLE
about 12-Hand Gesture Recognition_v2

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#12]
when we use this application,

in the case of "if(hand_count == 0 && thresh_score > 70)",
this message is shown ,
" with low confidence"

what does it mean?

**Comment by mohitb-ign** [comment]
The sample app is designed to show good accuracy during the demos.
This app has 2 modes : 

- Normal mode (Number of hands =1).
- Low confidence mode. (Number of hands =0).

Resnet-18 based hand gesture classifier operates on the full frame and not on the cropped image.  
TinyYoloV3 model detects number of hands visible in the frame.  It is used as an error handling mechanism at application level.

- If number of hands are more than 1 , an error is shown on the screen- "Multiple hands detected".
- If number of hands ==1 , Then it is called as normal mode.  Bounding box around detected hand is shown along with hand gesture text.
- In case, TinyYoloV3 could not detect a hand, but Resnet18 based hand gesture classifier shows good gesture detection confidence (more than 70% confidence), then the result of Resnet-18 based hand gesture classifier is displayed on the screen along with "Low confidence" message.

**Comment by a5111295** [comment]
thank you for your response.

I run this application, "Low confidence" message is often displayed.
the case that TinyYoloV3 could not detect a hand but Resnet-18 could classify handgestures,
often occured.
 "Low confidence" make confuse the user,therefore the message does not need to be displayed.

**Comment by mohitb-ign** [comment]
This minor update in output message is completed. Commit is made on main branch.

**Comment by a5111295** [comment]
Thank you for your reply.
 
I confirmed to delete "Low confidence".
