### ISSUE TITLE
Error of "Face_spoof_detection_img"

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#13]
Hello ,
I used "Face_spoof_detection_img" of "06-Face_recognition_spoof_detection
spoof_detection".
but there is error , when setting image size of not sample.bmp
---
[ERROR] Failed to run fread():error=0
[ERROR] Failed to read BMP file: sample.bmp

Could you please fix it ?

**Comment by mohitb-ign** [comment]
The issue is fixed now. Please check.

**Comment by a5111295** [comment]
Thank you for your quick response.

I have confirmed there are no errors.

but I replaced sample.bmp to another image,
the result display "Genuine Face Detected"

what does "Genuine Face Detected" means?

**Comment by mohitb-ign** [comment]
This application works in a binary classification mode. It shows 2 outputs.

1. **Spoofed Face Detected** - This means that the image is from phone screen.
2. **Genuine Face Detected** - This means that there is a real human in the image.

**Comment by a5111295** [comment]
Thank you for your reply.
I understood the diffrence of "Spoofed" and "Genuine".
I checked to detect spoofed picture from phone screen.
