### ISSUE TITLE
README of "06_Face_recognition_spoof_detection"

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#14]
Hello,

regarding README.md of the below,
https://github.com/Ignitarium-Renesas/RZV2L_AiLibrary/tree/main/06_Face_recognition_spoof_detection

There are a weird format such as L176~186.

could you please fix it?

**Comment by mohitb-ign** [comment]
Fixed it. 
Please have a look.

**Comment by a5111295** [comment]
Thank you for your quick response.

I have confirmed it.
this issues closed
