### ISSUE TITLE
detection of vest about 04-Helmet/Vest Detection

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#15]
Hello,
camera/image both application can not detect vests.(for example /test_images/10.jpg)
and they can not detect helmets(/test_images/1.jpg)

could you please check correct weight file or fix it?

**Comment by mohitb-ign** [comment]
Thanks for pointing it out. We will verify, fix and come back.

**Comment by mohitb-ign** [comment]
We have retrained the model and updated the weights file in the same release. Kindly have a look at the readme file to run it properly. The vest and helmet detections are proper within 150 centimeter distance.

**Comment by a5111295** [comment]
Hello,
Thank you for your improvement.

I checked the application could detect vest with retrained model.

I think dataset is the same one as before.
what is the reason?

**Comment by mohitb-ign** [comment]
Hello, 
Here are the improvements:
Newly used dataset : https://www.kaggle.com/datasets/muhammetzahitaydn/hardhat-vest-dataset-v3
This time,we trained with this set of hyper parameters:
1. 416x416 image sizes were considered while new training. (Default)
2. Batch-size considered is 64.(Default)
3. Trained upto 10,000 steps, but found the best working model at 8000 steps. (Max batches parameter).

All this helped in improving the detection.

**Comment by a5111295** [comment]
Thank you for your reply.

I understood the reason.
