### ISSUE TITLE
about Face_recognition_img

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#16]
hello,
about 06_Face_recognition_spoof_detection/Face_recognition_img,
current application can not detect unregistered person.
(in the case of unregistered person ,It seems shows the top name of the list.

could you fix it?

**Comment by mohitb-ign** [comment]
Thanks for pointing it out. We will verify, fix and come back.

**Comment by a5111295** [comment]
I understood the below situation.
---
The code works in following way -> DL model finds the face embeddings. (Kind of a feature vector for a human face). Then, these feature vectors are matched with the already registered feature vectors. For matching these two vectors (registered embedding and currently visible embedding) , a distance-based criteria is used.
