### ISSUE TITLE
about 12-Hand Gesture Recognition_v2

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#17]
hello,
when this application is runnning,
mode name has still displayed HRnet.

could you please fix it?

**Comment by mohitb-ign** [comment]
Thanks for pointing it out. We will verify, fix and come back.

**Comment by mohitb-ign** [comment]
We could not find the issue.
can you please help us pinpointing it?

Video output:
![Output_12](https://github.com/Ignitarium-Renesas/RZV2L_AiLibrary/assets/69347827/c403a2b4-8d18-48a1-8d75-2aa8e3f48754)

Searching in the source code:
![Hrnet-NA](https://github.com/Ignitarium-Renesas/RZV2L_AiLibrary/assets/69347827/0da91790-60a5-43b2-9c40-966c51b54b2f)

**Comment by a5111295** [comment]
Sorry, I missed the log file.

This application can show the correct model name
