### ISSUE TITLE
about 03_Elderly_fall_detection

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#18]
Hello,
in this application,
there are no comment of "The person 1 has fallen" on the display.
could you add this comment?

and how is progress of this application?

**Comment by mohitb-ign** [comment]
Thanks for pointing it out. We will verify, fix and come back.

I didn't understand the 2nd question. Can you please explain?

**Comment by a5111295** [comment]
I'm sorry ,about 2nd question, the description is shortage.
I heard this application has been ongoing improvement of performance and accuracy.
therefore I ask how is the progress of improvement.
