### ISSUE TITLE
about enhance of application

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#19]
if possible, could you please enhance the below application?
(priority is low.)

1.
01-Head Counting
04-Helmet/Vest Detection
05-Age/Gender Estimation
07-Animal Detection

about the image mode of the above application,
I would like you not to need to input width/height.
(width/height set will be optional)

2.
06-Face_recognition_spoof_detection/Face_regisration

currently, we can register the faces with wayland only.
it is better to be able to register them with teraterm.

3.
06-Face_recognition_spoof_detection/Face_recognition_cam

it is easy to set faces if there is not a square but a circle.

**Comment by mohitb-ign** [comment]
1. Inputting width/height was an initial requirement discussed. But w can make it optional for sure. We will update and come back.
2. We will check the possibilities and come back
3. We will check the possibilities and come back

**Comment by a5111295** [comment]
Hello,
I confirmed No1,No3.
AI SDK recommend using wayland.
therefore you do not need to improve No2.

this issue closed
