### ISSUE TITLE
creating branch

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#20]
hello,

we know you are developing applications with another gitlab.

we would like to manage developping branch,
could you please create a branch for develop?

**Comment by mohitb-ign** [comment]
Created a new branch 'development'.

**Comment by a5111295** [comment]
Thank you for your response.

regarding new applications from July, could you please develop them in this branch of "develop" only?

**Comment by mohitb-ign** [comment]
Allright. We will develop all the new applications in this newly created development branch.

**Comment by a5111295** [comment]
Thank you for your reply.
