### ISSUE TITLE
About Creatice Common license

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#21]
Hello,

in "12-Hand Gesture Recognition V2",
you are using "Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",

therefore could you please add the needed information for users?

reference
https://creativecommons.org/licenses/by-sa/4.0/deed.en

**Comment by mohitb-ign** [comment]
Additional info is added in the ReadMe file of this application : [Readme file Link](https://github.com/Ignitarium-Renesas/RZV2L_AiLibrary/blob/main/12_Hand_Gesture_Recognition_v2/README.md)
