### ISSUE TITLE
Change camera input size for 11_Head_count_topview

### ISSUE THREAD

**Issue by a5111295** [Ignitarium-Renesas/RZV2L_AiLibrary#25]
About 11_Head_count_topview, we would like to change the MIPI camera input size from 640x480 to 1280x720 because we use our camera.

Is it correct that we need to change the below?
Or Is another sorce code needed to be changed too?

<define.h>
/*Camera Capture Image Information*/
#define USB_CAM_IMAGE_WIDTH         (640)
#define USB_CAM_IMAGE_HEIGHT        (480)
:
/*Camera Capture Image Information*/
#define CAM_IMAGE_WIDTH             (640)
#define CAM_IMAGE_HEIGHT            (480)

**Comment by LolikaPadmanabhan** [comment]
Thanks for trying this application.

Yes. along with that you need to make the following changes as well.

1. Changes in prepost_yolov3_headcount_top_cam.yaml

		#######################################
		# Input data
		#######################################
		input_to_pre:
		  -
		    name: "yuv_data"
		    format: "YUY2"
		    order: "HWC"
		    shape: [720, 1280, 2]
		    type: "uint8"
 
2. Changes in define.h

	/*Camera Capture Image Information*/
	#define USB_CAM_IMAGE_WIDTH         (1280)
	#define USB_CAM_IMAGE_HEIGHT        (720)
	#define USB_CAM_IMAGE_CHANNEL_YUY2  (2)
 
	#define CAM_IMAGE_WIDTH             (1280)
	#define CAM_IMAGE_HEIGHT            (720)
	#define CAM_IMAGE_CHANNEL_YUY2      (2)
 
	#define RESIZE_SCALE                (1.0)

**Comment by a5111295** [comment]
thank you for your reply.
I will close this issue

**Comment by a5111295** [comment]
Hello,
the above No1,2 have been changed,
however bounding box is not displayed correctly.

aside from No1,2 ,  which source code  will we have to change?
