### ISSUE TITLE
Face_registration application does not capture the image.

### ISSUE THREAD

**Issue by wk-mnA** [Ignitarium-Renesas/RZV2L_AiLibrary#6]
When I run the Face_registration application and selected "0", which means capturing new face, nothing happend and the log stayed the same like below.
```
---------------------------
..Press Enter to capture..
---------------------------

* pressed ENTER but nothing happend.
```
After I terminated the application with Ctrl+C, "captures" directory is created in application directory, but capture image files does not exist. 
Is there any procedures that I have missed?

**Comment by mohitb-ign** [comment]
RZV2L board must have a keyboard connected to it. The "Enter" key of the physically connected keyboard should be pressed.
When you press enter key from an ssh session (or remote session) it wont work.
Can you please confirm if you are hitting 'Enter' key from a physically connected keyboard?

**Comment by wk-mnA** [comment]
Thank you for the reply.
It worked when typing ENTER key on the wayland screen.
